target_dir = "/tmp/fintl-dev"

[sources.dkb]
giro      = "tests/accounts_etl/files/csv_files/DKB/kontoauszug"
tagesgeld = "tests/accounts_etl/files/csv_files/DKB/tagesgeld"
credit    = "tests/accounts_etl/files/csv_files/DKB/credit"

[sources.postbank]
giro = "tests/accounts_etl/files/csv_files/Postbank"

[sources.scalable]
broker = "tests/accounts_etl/files/html_files/Scalable-Capital"

[sources.gls]
giro   = "tests/accounts_etl/files/csv_files/GLS/giro"
credit = "tests/accounts_etl/files/csv_files/GLS/credit"
